### ISSUE TITLE
全てのヘルプを参照する際にIndexOutOfRangeExceptionが出る

### ISSUE THREAD

**Issue by Potato1682** [P2P-Develop/Chat-Chan-Debug#1]
**説明**
`help`で全てのヘルプを参照しようとするとIndexOutOfRangeExceptionが発生しました。
ログ:
[*]System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Chat_Chan_Debug.Command.CommandHelp.Execute(String label, String[] args)
   at Chat_Chan_Debug.Command.CommandManager.Execute(String commandName, String[] arg)
   at Chat_Chan_Debug.Program.Main()

**バグ再現**
以下の手順でバグが発生しました。
1. `help`とコマンドを入力してEnterキーを押下する。
2. バグ発生

**デスクトップ環境**
 - OS: Windows 10 1903
 - .NET Core バージョン: 3.1
 - バージョン 1.2.0-pre1

**補足**
既知のバグのうち一つのバグです。

**Comment by Potato1682** [comment]
修正しました。
